'use client';
import { useState } from 'react';

const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000';
type Block = { id: number; type: string; text: string };
const initialBlocks: Block[] = [{ id: 1, type: 'hero', text: 'Build something remarkable' }, { id: 2, type: 'text', text: 'Tell your story with a beautiful Cristal website.' }, { id: 3, type: 'button', text: 'Get started' }];

export default function BuilderPage() {
  const [blocks, setBlocks] = useState(initialBlocks); const [selected, setSelected] = useState(1); const [saving, setSaving] = useState('');
  const move = (index: number, direction: -1 | 1) => { const next = index + direction; if (next < 0 || next >= blocks.length) return; const copy = [...blocks]; [copy[index], copy[next]] = [copy[next], copy[index]]; setBlocks(copy); };
  const add = (type: string) => setBlocks([...blocks, { id: Date.now(), type, text: type === 'image' ? 'Image placeholder' : type === 'button' ? 'Click me' : 'New content block' }]);
  async function save() { const token = localStorage.getItem('cristalToken'); const id = localStorage.getItem('cristalWebsiteId'); if (!token || !id) { setSaving('สร้างเว็บจากหน้า Builder หรือเข้าสู่ระบบก่อน'); return; } const response = await fetch(`${API}/api/websites/${id}`, { method: 'PATCH', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ pages: { home: { blocks } } }) }); setSaving(response.ok ? 'บันทึกแล้ว' : 'บันทึกไม่สำเร็จ'); }
  return <main className="min-h-screen bg-slate-100 p-4 text-ink"><div className="mx-auto max-w-7xl"><div className="mb-4 flex items-center justify-between rounded-2xl bg-white p-4 shadow"><h1 className="text-2xl font-black text-violet">Cristal Canvas ✦</h1><button onClick={save} className="rounded-xl bg-violet px-5 py-2 font-bold text-white">Save changes</button></div><div className="grid gap-4 lg:grid-cols-[220px_1fr_280px]"><aside className="rounded-2xl bg-white p-4 shadow"><h2 className="font-black">Blocks</h2>{['hero','text','image','button'].map((type) => <button key={type} onClick={() => add(type)} className="mt-3 block w-full rounded-xl bg-slate-100 p-3 text-left font-semibold hover:bg-purple-100">＋ {type}</button>)}</aside><section className="min-h-[650px] rounded-2xl bg-white p-8 shadow"><div className="mx-auto max-w-2xl space-y-4">{blocks.map((block, index) => <div key={block.id} draggable onDragStart={() => setSelected(block.id)} onClick={() => setSelected(block.id)} className={`cursor-grab rounded-2xl border-2 p-6 ${selected === block.id ? 'border-violet bg-purple-50' : 'border-transparent bg-slate-50'}`}><p className="mb-2 text-xs font-bold uppercase text-violet">{block.type}</p><p className={block.type === 'hero' ? 'text-4xl font-black' : block.type === 'button' ? 'inline-block rounded-xl bg-violet px-4 py-2 font-bold text-white' : 'text-lg'}>{block.text}</p></div>)}</div></section><aside className="rounded-2xl bg-white p-4 shadow"><h2 className="font-black">Inspector</h2>{blocks.map((block, index) => selected === block.id && <div key={block.id} className="mt-4"><label className="text-sm font-bold">Content</label><textarea value={block.text} onChange={(e) => setBlocks(blocks.map((item) => item.id === block.id ? { ...item, text: e.target.value } : item))} className="mt-2 h-28 w-full rounded-xl bg-slate-100 p-3" /><div className="mt-3 flex gap-2"><button onClick={() => move(index, -1)} className="rounded-lg bg-slate-100 px-3 py-2">↑</button><button onClick={() => move(index, 1)} className="rounded-lg bg-slate-100 px-3 py-2">↓</button></div></div>)}{saving && <p className="mt-5 text-sm font-bold text-violet">{saving}</p>}</aside></div></div></main>;
}
