'use client';

import Navbar from '../../components/navbar';

const sites = [{ title: 'CoffeeBloom', domain: 'coffeebloom.cristal.page', status: 'Published', views: '3.2k', date: 'Oct 5, 2024 10:32 AM' }, { title: 'Luna-Design', domain: 'lunadesign.cristal.page', status: 'Draft', views: '842', date: 'Oct 4, 2024 16:10 PM' }];

export default function DashboardPage() { return <main className="min-h-screen bg-[#edf1fa] p-4 text-ink md:p-8"><Navbar /><div className="mx-auto max-w-7xl"><div className="mt-8 flex flex-wrap items-end justify-between gap-4"><div><p className="font-bold text-violet">GOOD MORNING, CREATOR ✦</p><h1 className="mt-1 text-4xl font-black">Your Websites</h1></div><button className="rounded-xl bg-gradient-to-r from-violet to-coral px-6 py-3 font-bold text-white">+ Build New Website with AI</button></div><div className="mt-8 grid gap-5 md:grid-cols-3"><Stat label="Active Websites" value="5" hint="↗ 2 this month" /><Stat label="AI Credits" value="1,240" hint="460 used this month" /><Stat label="Total Visitors" value="12.4k" hint="↗ 18% vs last month" /></div><section className="mt-8 rounded-3xl bg-white p-6 shadow-soft"><div className="mb-4 flex items-center justify-between"><h2 className="text-2xl font-black">Your Websites</h2><span className="rounded-full bg-purple-100 px-3 py-1 text-sm font-bold text-violet">Pro · 499 THB/month</span></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead className="border-b text-sm text-slate-500"><tr><th className="px-4 py-3">Website</th><th>Status</th><th>Views</th><th>Last edited</th><th className="text-right">Action</th></tr></thead><tbody>{sites.map((site) => <tr key={site.title} className="border-b last:border-0"><td className="px-4 py-5"><p className="font-bold">💎 {site.title}</p><span className="text-sm text-slate-500">{site.domain}</span></td><td><span className={`rounded-full px-3 py-1 text-xs font-bold ${site.status === 'Published' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>{site.status}</span></td><td className="font-semibold">{site.views}</td><td className="text-sm text-slate-500">{site.date}</td><td className="text-right"><button className="rounded-xl bg-gradient-to-r from-violet to-coral px-5 py-2 font-bold text-white">Edit</button></td></tr>)}</tbody></table></div></section></div></main>; }

function Stat({ label, value, hint }: { label: string; value: string; hint: string }) { return <div className="rounded-3xl bg-white p-6 shadow-soft"><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-2 text-4xl font-black">{value}</p><p className="mt-2 text-sm font-bold text-emerald-600">{hint}</p></div>; }
