'use client';

import { FormEvent, useState } from 'react';
import Link from 'next/link';

const gallery = [
  { title: 'Coffee Shop Landing', creator: 'CoffeeBloom', category: 'E-commerce', tone: 'coffee', badge: 'Generated just now' },
  { title: 'Designer Portfolio', creator: 'Luna Design', category: 'Portfolio', tone: 'designer', badge: 'Generated 2h ago' },
  { title: 'Bakery Store', creator: 'Sweet Rise Bakery', category: 'Store', tone: 'bakery', badge: 'Generated yesterday' },
];

export default function HomePage() {
  const [idea, setIdea] = useState('');
  const [submitted, setSubmitted] = useState(false);
  const submit = (event: FormEvent) => { event.preventDefault(); setSubmitted(true); };

  return <main>
    <header className="mx-auto mt-4 flex max-w-[1790px] items-center justify-between rounded-[26px] bg-white px-8 py-4 shadow-soft md:px-12">
      <Link href="/" className="flex items-center gap-3 text-3xl font-extrabold tracking-tight text-ink"><span className="crystal-mark">✦</span>Cristal Builder</Link>
      <nav className="hidden gap-9 text-[15px] font-semibold text-slate-700 md:flex"><a href="#product">Product</a><a href="#gallery">Templates</a><a href="#pricing">Pricing</a><Link href="/dashboard">Dashboard</Link><a href="#resources">Resources</a></nav>
      <div className="flex gap-3"><Link href="/login" className="rounded-xl border-2 border-ink px-5 py-2.5 font-bold">Log in</Link><Link href="/register" className="rounded-xl bg-gradient-to-r from-violet to-coral px-6 py-3 font-bold text-white shadow-lg">Get Started</Link></div>
    </header>

    <section id="product" className="cristal-bg mt-4 px-5 py-16 text-center md:py-20"><p className="mb-3 font-bold uppercase tracking-[.25em] text-violet">✦ AI website generator</p><h1 className="mx-auto max-w-4xl text-5xl font-black leading-tight text-ink md:text-7xl">Build your website with AI in seconds</h1><p className="mx-auto mt-5 max-w-3xl text-lg font-medium text-slate-800 md:text-xl">Describe your idea and Cristal Builder will design, create, and launch a beautiful website for you — instantly.</p>
      <form onSubmit={submit} className="mx-auto mt-9 flex max-w-5xl flex-col gap-3 rounded-3xl bg-white p-3 shadow-2xl md:flex-row"><span className="hidden items-center px-4 text-2xl md:flex">✦</span><input value={idea} onChange={(e) => setIdea(e.target.value)} placeholder="Tell Cristal your idea" className="min-w-0 flex-1 rounded-2xl bg-transparent px-4 py-4 text-xl outline-none" /><button className="rounded-2xl bg-gradient-to-r from-violet to-coral px-9 py-4 text-lg font-extrabold text-white">Generate →</button></form><p className="mt-4 text-sm font-semibold text-slate-700">💡 Try: “coffee shop with online order” · “photographer portfolio” · “startup landing for SaaS app”</p>{submitted && <p className="mt-3 font-bold text-violet">Your idea is ready — connect the AI engine to generate “{idea || 'your website'}”.</p>}
    </section>

    <section id="gallery" className="mesh-bg px-5 py-12 md:px-12"><div className="mx-auto max-w-7xl text-center"><h2 className="text-4xl font-black text-ink">Gallery — Websites Created by AI</h2><p className="mt-2 text-lg text-slate-700">Thousands of beautiful sites generated by Cristal AI. Get inspired or remix one to make it yours.</p><div className="mt-8 grid gap-6 md:grid-cols-3">{gallery.map((item) => <article key={item.title} className="overflow-hidden rounded-2xl bg-white text-left shadow-soft"><div className={`preview-art ${item.tone}`}><span>✦ {item.badge}</span><div className="preview-window">{item.tone === 'coffee' ? '☕ CoffeeBloom' : item.tone === 'designer' ? 'Luna Design' : '🥐 Sweet Rise'}</div></div><div className="p-5"><h3 className="text-xl font-extrabold">{item.title}</h3><p className="mt-1 text-sm text-slate-600">♧ {item.creator} · {item.category}</p><div className="mt-4 flex gap-4 font-bold text-violet"><button>Remix</button><button>Preview</button></div></div></article>)}</div></div></section>

    <section id="pricing" className="bg-[#e8e2ff] px-5 py-14"><div className="mx-auto max-w-6xl text-center"><h2 className="text-4xl font-black">Simple, transparent pricing</h2><p className="mt-2 text-lg">Start free. Upgrade when you&apos;re ready to publish and grow.</p><div className="mt-8 grid gap-6 text-left md:grid-cols-2">{[['Starter','199 THB','Up to 3 websites','AI generation — 50 credits/month','Custom domain','Basic templates & components'],['Pro','499 THB','Advanced AI design & branding','Team collaboration (5 members)','Priority 24/7 support','Analytics & SEO tools']].map(([name, price, ...features], index) => <div key={name} className="rounded-3xl bg-white p-7 shadow-soft"><div className="flex items-start justify-between"><div><h3 className="text-2xl font-black">{name}</h3><p className="mt-4 text-4xl font-black text-violet">{price}<small className="text-sm text-slate-500"> /month</small></p></div>{index === 1 && <span className="rounded-full bg-coral px-3 py-1 text-xs font-bold text-white">MOST POPULAR</span>}</div><ul className="my-6 space-y-3">{features.map((feature) => <li key={feature} className="font-medium">✅ {feature}</li>)}</ul><Link href="/register" className="block rounded-xl border-2 border-violet py-3 text-center font-bold text-violet">Start {name}</Link></div>)}</div></div></section>
    <footer className="bg-[#171536] px-6 py-6 text-center text-sm text-white">© 2024 Cristal Builder · Made with ✦ AI · Help · Terms · Privacy · Discord community</footer>
  </main>;
}
