'use client';

import { useState } from 'react';
import Navbar from '../../components/navbar';

const posts = [
  { author: 'Alex Chen', initials: 'AC', time: '2h', text: 'Just found this amazing minimalist portfolio design — clean, modern and inspiring for my own site!', title: 'Minimalist Portfolio Design 2024 — Clean & Modern UI', detail: 'A collection of modern portfolio design layouts, animations and responsive components.', likes: 124, comments: 18, shares: 5, color: 'bg-slate-900' },
  { author: 'Maya Liu', initials: 'ML', time: '5h', text: 'Sharing my new productivity dashboard built in Notion — helps me plan weekly goals and track habits!', title: 'Productivity Dashboard Template — Plan, Track & Focus', detail: 'Custom dashboard for personal productivity, habit stacking and goal planning.', likes: 89, comments: 12, shares: 3, color: 'bg-teal-50' },
  { author: 'Jordan Patel', initials: 'JP', time: '1d', text: 'Open-sourcing our Cristal community toolkit on GitHub! Feedback welcome 🙌 built in public', title: 'cristal-open / cristal-toolkit', detail: 'Reusable UI components, design system and docs for the Cristal community.', likes: 256, comments: 34, shares: 21, color: 'bg-[#171536]' },
];

export default function CommunityPage() {
  const [liked, setLiked] = useState<string[]>([]);
  const toggleLike = (author: string) => setLiked((current) => current.includes(author) ? current.filter((item) => item !== author) : [...current, author]);
  return <main className="min-h-screen bg-[#edf1fa] p-4 text-ink md:p-8"><Navbar /><div className="mx-auto mt-8 grid max-w-7xl gap-7 lg:grid-cols-[360px_1fr]"><aside className="space-y-6"><div className="rounded-3xl bg-gradient-to-br from-violet to-[#7043ff] p-8 text-white shadow-soft"><h1 className="text-4xl font-black">Join Cristal</h1><p className="mt-3 text-lg">Discover & share the best websites. Connect with creators worldwide.</p><button className="mt-8 w-full rounded-2xl bg-[#5414e8] py-4 text-lg font-black">Join Cristal ✦</button></div><div className="rounded-3xl bg-white p-7 shadow-soft"><h2 className="text-2xl font-black">Trending Tags</h2><div className="mt-5 flex flex-wrap gap-2">{['#DesignInspo','#WebDev','#Productivity','#UIUX'].map((tag) => <span key={tag} className="rounded-xl bg-purple-100 px-3 py-2 text-sm font-bold text-violet">{tag}</span>)}</div><h2 className="mt-8 text-2xl font-black">Community</h2><p className="mt-3 font-semibold">Creators 12.4k · Online 1.2k <span className="text-emerald-600">● Active now</span></p><div className="mt-5 rounded-2xl bg-slate-100 p-4"><p className="font-bold">☑ Weekly Goals</p><p>☐ Habits Tracker</p><p>☐ Reading List</p></div></div></aside><section><div className="mb-6 flex items-center gap-4 rounded-3xl bg-white p-4 shadow-soft"><span className="avatar">C</span><input placeholder="Share a website to the Cristal community..." className="min-w-0 flex-1 rounded-2xl bg-slate-100 px-5 py-4 outline-none" /><span className="hidden text-emerald-600 md:block">▣ Photo</span><span className="hidden text-violet md:block">🔗 Website</span><span className="hidden text-amber-600 md:block">▱ Poll</span></div>{posts.map((post) => { const isLiked = liked.includes(post.author); return <article key={post.author} className="mb-6 rounded-3xl bg-white p-5 shadow-soft md:p-7"><div className="flex items-center gap-3"><span className="avatar">{post.initials}</span><div><h2 className="font-black">{post.author} <span className="font-normal text-slate-500">· {post.time} · ◉ Public</span></h2></div><button className="ml-auto text-2xl text-slate-500">•••</button></div><p className="my-5 text-lg font-medium">{post.text}</p><div className={`rounded-2xl ${post.color} p-5 text-white`}><h3 className="text-lg font-black">{post.title}</h3><p className="mt-2 text-sm opacity-85">{post.detail}</p><button className="mt-4 rounded-xl bg-white/15 px-4 py-2 font-bold">⚡ Remix Web</button></div><div className="mt-5 flex justify-between border-t pt-4 text-sm font-semibold text-slate-600"><button onClick={() => toggleLike(post.author)} className={isLiked ? 'text-pink-600' : ''}>♥ {post.likes + (isLiked ? 1 : 0)} likes</button><button>▢ {post.comments} comments</button><button>↗ {post.shares} shares</button></div></article>; })}</section></div></main>;
}
